-   id: isort
    name: isort
    description: "Runs isort over python source.  If you configure additional arguments you'll want to at least."
    entry: isort
    language: python
    types: [python]
    args: []
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
